#ifndef MEMORY_ADDRESSES_H
#define MEMORY_ADDRESSES_H

#include "common_defs.h"

//#define SHARED_MEM_BASE (0x100000)
#define SHARED_MEM_BASE (0x100000 | 0x80000000)

#define IMAGE_READ_BUF_A SHARED_MEM_BASE
#define IMAGE_READ_BUF_B (IMAGE_READ_BUF_A + IMAGE_SIZE)
#define IMAGE_READ_BUF_C (IMAGE_READ_BUF_B + IMAGE_SIZE)

#define SHARED_ACCEL_DATA (IMAGE_READ_BUF_C + IMAGE_SIZE)
#define SHARED_DISPLAY_STATE (SHARED_ACCEL_DATA + sizeof(SharedAccelData))

#define PROCESSED_IMG_BUF (SHARED_DISPLAY_STATE + sizeof(SharedDisplayState))

#endif
